### PR TITLE
Add new S3 documentation. 

### PR DESCRIPTION
**Pull request by SC2Mitch**
This pull includes the following
- Added new S3 configuration and guides
- Adds a new path to `docs/.vuepress/config.js` but I need to test that. 

Things to do: Test to make sure it works, update other documentation where needed. 

Requests and comments are appreciated.

### CODE REVIEW

**Comment by Vaalyn** [comment]
Could you add the example image from the introduction to the repository instead of using imgur?
(Images are placed in this directory:https://github.com/AzuraCast/azuracast.com/tree/master/docs/.vuepress/public/img)

You might also wanna replace the local path in that screenshot with something that looks like a prefix on an S3 bucket in order to avoid confusion (for example `/bucket_media`). I could imagine that this could be misunderstood as of now.

**Comment by SC2Mitch** [comment]
> Could you add the example image from the introduction to the repository instead of using imgur?
> (Images are placed in this directory:https://github.com/AzuraCast/azuracast.com/tree/master/docs/.vuepress/public/img)
> 
> You might also wanna replace the local path in that screenshot with something that looks like a prefix on an S3 bucket in order to avoid confusion (for example `/bucket_media`). I could imagine that this could be misunderstood as of now.

Amendments made.

**Comment by Vaalyn** [comment]
> It could take up to a hour for the files to fully process 100 files for example. If it takes more than a few hours, contact us through our support methods.

That sounds/reads a bit weird, would recommend changing it to something like:

> For example with a really slow S3 provider processing 100 files could take up to an hour.
> If the processing seems slow to you please measure the download speeds of your S3 bucket to determine if this is an issue with the S3 providers resources before contacting us through our support methods.

**Comment by SC2Mitch** [comment]
I agree the wording on it was a little strange, I've made some adjustments to it.

**Review by Vaalyn — APPROVED** [review]
LGTM 👍

**Pull request merged**
