### PR TITLE
Update screenshots and IceCast information

### PR DESCRIPTION
**Pull request by SC2Mitch**
Needs bit of testing first before I'm done with it.

### CODE REVIEW

**Comment by SC2Mitch** [comment]
All good, ready for review.

**Comment by Vaalyn** [comment]
Could you rename `tour_update.gif` to `ScreenshotTour.gif` / overwrite the existing one with that name?

Same for `admin_update.png` and `login_screen_update.png`. Better update the files themself instead of adding one with `_update` at the end.

**Comment by SC2Mitch** [comment]
Uno momento.

**Comment by SC2Mitch** [comment]
@Vaalyn Any other requests / changes?

**Comment by Vaalyn** [comment]
> @Vaalyn Any other requests / changes?

From my side all looks good 👍

**Pull request merged**
